import type { Metadata } from "next";
import Link from "next/link";
import { listSales } from "@/server/os/sales";
import { getOsSettings } from "@/server/os/settings";
import { ExcelTools } from "@/components/os/excel-tools";
import { Card, EmptyState, Money, PageHead, Pagination, Pct, StatusBadge, Table, Td, Th, Tr, btn } from "@/components/os/ui";
export const metadata: Metadata = { title: "Satışlar · Business OS" }; export const dynamic = "force-dynamic";
type SP = Promise<{ q?: string; status?: string; page?: string }>;
export default async function SalesPage({ searchParams }: { searchParams: SP }) { const sp=await searchParams; const [data,s]=await Promise.all([listSales({search:sp.q,status:sp.status as never,page:Number(sp.page)||1}),getOsSettings()]); return <><PageHead title="Satışlar" description="Satış onaylandığında stok, kâr ve tahsilat planı birlikte oluşur." actions={<Link className={btn.primary} href="/os/sales/new">+ Satış</Link>}/><div className="mb-4 flex justify-end"><ExcelTools entity="sale" entityLabel="Satışlar" exportHref="/os/export?kind=sales"/></div><Card padded={false}>{data.rows.length ? <><Table stacked><thead><tr><Th>Belge</Th><Th>Tarih</Th><Th>Müşteri</Th><Th>Kanal</Th><Th align="right">Tutar</Th><Th align="right">Kâr</Th><Th align="right">Marj</Th><Th>Durum</Th></tr></thead><tbody>{data.rows.map(r=><Tr key={r.id}><Td><Link className="font-medium hover:underline" href={`/os/sales/${r.id}`}>{r.code}</Link></Td><Td label="Tarih">{r.issuedAt.toLocaleDateString("tr-TR")}</Td><Td label="Müşteri">{r.customerName??"—"}</Td><Td label="Kanal">{r.channelName??"—"}</Td><Td label="Tutar" align="right"><Money value={r.total} currency={r.currency}/></Td><Td label="Kâr" align="right"><Money value={r.profit} currency={s.baseCurrency}/></Td><Td label="Marj" align="right"><Pct value={r.marginPct}/></Td><Td label="Durum"><StatusBadge status={r.status}/></Td></Tr>)}</tbody></Table><Pagination {...data} baseHref="/os/sales"/></> : <EmptyState title="Henüz satış yok" description="İlk satışını oluşturduğunda stok ve kâr burada görünür." action={<Link href="/os/sales/new" className={btn.primary}>+ Satış oluştur</Link>}/>}</Card></> }
